name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c68dd3fc4d1f895bb1c5404c0244c485ebd69e7a102dc626eaf2d0fe58d8745a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
