name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b769ad16ccc962309e6fdee2d8c8a655c0202f04707398722cec85f11f825224"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
