name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e59b8e265b00df41fba090978e9814ef5a8280cc7a7dd6cf721ee89d64a72dc"

[versions]
forge = "0.3.4-alpha"
minecraft = "1.12.2"
