name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cb8d8f46b2a32ecb100e529e6d13e9edde3ee17786b3c483893ee0c073e7f1a"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
