name = "\u001b[A\u001b[BProject Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cccd74e1909218b42e9882faadae01e6e6de76723ffdc00daa7565c18110aa1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
