name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d36f3b1d9ba17751333be42e52f088dcfd759583c783410a4763024019137615"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
