name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e2c44b0a1202125db0f4281e09051821c64fac4faa93a082194de63e822b415"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
