name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7c534ca09e05d55c176b594f81658f8039976f20defed086b6fc67679a33817"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
