name = "Project Virulence"
author = "HydratedBean"
version = "2024.2.3a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7380018547515eb261baa248f82cb1fb3e6dc1ea79580b48036f4b47df5ccffc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
