name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "193a67f7514d15828fab12ecb5b2e468fb4461591b57e2468972efc34df6ece4"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
