name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffdccd970d4dc45ce460ac90efd30b3fb473f613f4c5e195123435aba043af73"

[versions]
forge = "0.3.4-alpha"
minecraft = "1.12.2"
