name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a28d5ec697850d199071ad9b77357102615b408c29c7b3d5e5495f3aebe08f10"

[versions]
forge = "0.3.0-alpha"
minecraft = "1.12.2"
