name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e852ffef9253f5a0689cbc6bdfd5f27baa57633c6ec29ed73309efe7265acfe7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
