name = "\u001b[A\u001b[BProject Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21ffd33e91ece8d40d7a502a30672b4ced842a709739b83576f0dab20c4a2928"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
