name = "\u001b[A\u001b[BProject Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7c3ff781a0978bdf4b06d12557624870c5151d5056ea0cc00ee063e54e6b866"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
