name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ff7534368e4c16fd679b4ec79e256b8c68a629b0a7679eea455f57831341a88"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
