name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e4f9265ca735551c193ff70450a7c2b27d9db8f56b9fbedcb0fdcffd1037e6f"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
