name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6ab39e1dc044cd65414491247c6ce3fee8d902327e681c6c4921c858a93f850"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
