name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b5c3b7272d5d7ec4489517731b00a1c9bb2bb3bf0bbc04fae5ee8a50f077bb7"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
