name = "\u001b[A\u001b[BProject Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99ec7bbd3486c90e2e216cf5aec38fe6660384bfae3713e0f0e3e891b2931408"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
