name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4db4dce8a96a7902a96fcf4ee08fcffecb3cd24fc656eb6a4062c46eba9446e7"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
