name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de726e4f0dc906cfe97f18e085d9abb6a24192407850fad1b8ba39e496c7718b"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
