name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27d77575060a203cfabb35b8ba6228fb4cbe507d140f1d1526e3eb61d6417a4a"

[versions]
forge = "0.3.7-alpha"
minecraft = "1.12.2"
