name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10c5eea3bc96c05d859b10cc93784e07c2fa8aeecf3024940894dd432e13bfa5"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
