name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe182a6ce817a1b774697c1f412f1b982dc0514e041512a4d57c6807485d2cf"

[versions]
forge = "0.3.10-alpha"
minecraft = "1.12.2"
