name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a440e9ee67a301bbdd306570f1e119ffda4e17e52bb34a8fae9c96f22b1e5db1"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
