name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "132c5d5a71e6a6881b005f8f50e335ca0355f1cde19bc876860770e533731c80"

[versions]
forge = "0.3.10-alpha"
minecraft = "1.12.2"
