name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbb8350d38ae9b6fe57674a795254331c22590a8e58d7b16235d6d50d4e7b295"

[versions]
forge = "0.3.7-alpha"
minecraft = "1.12.2"
