name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d01b1ded8104d7bdaf958d27f333fcac019fc9234706688aaff6f6fb30bbb78"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
