name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ad7d8d4062c0ac48c9c263916c2ba31603590abab54174d6dacba39fe49b25f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
