name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bba8f56905f4b9dd57ef4dc0498e1cd7500ea3e6cd06f74b5bd397f141489b8a"

[versions]
forge = "0.3.10-alpha"
minecraft = "1.12.2"
