name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2828f0b73a71f0ae07211a510d31b722884d421ff6a494e9ad0b010da67f67cd"

[versions]
forge = "0.3.7-alpha"
minecraft = "1.12.2"
