name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "701c7d4ad4194a50e1ba6133836d8c9d534a7fe31398b8c1cb63c3f32cf95ba3"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
