name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a096e19259910dbc0bb187c09f777ed96842f675ae259655ac8e119a88eb3cd4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
