name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b9d19d5fcae3c60687ff165746488241ebb8329e77dc6283201042e1e6d9387"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
