name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad4fb55b2c08f2099e7c127a849142636a4d45cee75e8a8cba2e75858abcdb43"

[versions]
forge = "0.3.0-alpha"
minecraft = "1.12.2"
