name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03d0a22d5770cc11ce5c88e7ce633ac9d0bfe914347152cbca358969bd533a1e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
