name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "388cb2382637035117407fd90d164dffbab9082dffae28aa225b47a979f7496a"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
