name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf0ef584f73bc8085cd70ae27a2f31471a31939b0cc4cba09b443011a9d211b1"

[versions]
forge = "0.3.0-alpha"
minecraft = "1.12.2"
