name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95b3436e1432f1258b532f2f75926a58eb453cd95abb4269103274990c2edfd8"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
