name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3cde442b46c5040051449b173385860358c65d8d80c5ce9e75ee1bd1184a0dd"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
