name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a28f308ccaf844313917fbc6a5c645952089d991dfffc587cdc10c68396ed62"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
