name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b8dec0e22637da1caf228e792993fa4caf5a334c02c4b583f48979027de8ca9"

[versions]
forge = "0.3.7-alpha"
minecraft = "1.12.2"
