name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0292e765d4b8142f155ece42a5897eef611b1874db97ea00080e5213f837f75"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
