name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03f5773af566bc0f207fbcbd56a64ffb33c0f1b450b8878ac10fcf9a2c404f72"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
