name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0da26d3eaf418b9e6cc0f595abcf7121cda7f780ae82fb47a6f05ba2db0475db"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
