name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a722618e37d5dbc2ce0a506766f041e75c947e06f7e290ca5f34ce49eba3446"

[versions]
forge = "0.3.10-alpha"
minecraft = "1.12.2"
