name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9960a502e5d97bf5e604a369e0e7c85ebbef6ab07bdd62a2fabc8d6960f8f60a"

[versions]
forge = "0.3.4-alpha"
minecraft = "1.12.2"
