name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "402bf2aebc8cc67bec41e4675737821de558b7054f82ceec4ab81910e86076f7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
