name = "\u001b[A\u001b[BProject Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90516c3849eb4f9c37103d1e377b58af7786335871bbb11e2bfeba6beecf2740"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
