name = "\u001b[A\u001b[BProject Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "174c8c5acf887c5d4e6473ae3801db2625a4cf8aa029d1f8de91e7ece9ddabce"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
