name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e4382af9aaadffa02606bb4e4fddf963ae808365e12e30097b7f7604c0241d6"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
