name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "732aa2b35856eae1054b26959fa357290280948801eb162aa473612b798b51de"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
