name = "\u001b[A\u001b[BProject Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a971c87645f0da7ac9473ef5551bd442738339cc3743f640e7c972f063e3810e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
