name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8903144182ee2d13777b43b12e30611ea57d95be0b024226e0864295dbd5fafb"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
