name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c18b38fe40ff1d5735939c799aa1269db62ddf2c60575481d0b6fd2c6655544"

[versions]
forge = "0.3.10-alpha"
minecraft = "1.12.2"
