name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1304d0adf7ff2d9b30171e84d5f6eba0e623814bdebe2b959d9e91f27aaa672c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
