name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35f2ef774aab3b5b1df7ba1b5ccba745d02c75dee95264fbcb76d50e4e93c6de"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
