name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bd58e977443e9c9c24437d23fd2795880751b48e187f5cdc364e66dceec4ad6"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
