name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f61d21f5448e2382a257d76bc504128e42bd97d21918021b1ede5c0169aa8bc9"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
