name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "074f57ea28eae882b961d6ed25a88bda8d17745ebe6490016d4364f0947f84c0"

[versions]
forge = "0.3.7-alpha"
minecraft = "1.12.2"
