name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68dd90473d8de7b6f9564d5ecdf91de4e0bb55fcfd5a4672529a4a01146ac2df"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
