name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72eba4b01b9272d2a2d3ea8c02646640761e6fed43887b049d50da6cc6541ce2"

[versions]
forge = "0.3.10-alpha"
minecraft = "1.12.2"
