name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e7e23e857c51038a964d62723548150d6602bc77fd52206fae660d0066496f1"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
