name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d8fd24659c8755fcb7bf9ab6fe21add47ffc96ae6bfb98cd839a522613748e9"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
