name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd104c3fcb430a873ce1747839980186628f86f7077692b1436553d3f037c0be"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
