name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4149369afa92345544e6b8a397c3ae01bcdd2c2f4d24c7de7a716f66e71fc18d"

[versions]
forge = "0.3.2-alpha"
minecraft = "1.12.2"
