name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c319af0811937d114297e68ceb927a088bf4c6c9caeb936b4b2bd4a7a8352f87"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
