name = "\u001b[A\u001b[BProject Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58e31501ecd504eb081eec1451d65f195b01b80929d44f7450a8629bd831a97f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
