name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c53177633e4da7b7f53e69904e8fab23c291d4b4e568df76e19d732654710e6f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
