name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "243c700b3f3205e0170b769cae8b807f1cd8bc526f42b7ce76a5e1ea99114dcf"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
