name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bb034902e07f03c4e364103b1114b16a5a76542f6963e4387f83db1242e75f6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
