name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69bfc313cff525615b1b77550f1da98646da40e6727365812fd0ffd3baaa3be3"

[versions]
forge = "0.3.10-alpha"
minecraft = "1.12.2"
