name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae3fcdbc2bef019ce6de11fce1d99814a74ad75adbcc6931f93258300ac00374"

[versions]
forge = "0.3.13-alpha"
minecraft = "1.12.2"
