name = "Project Virulence"
author = "HydratedBean"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c7a0fe7ec544c9e3c22218564ef584503ef6e8c773c2ce6b391dade7735cb65"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
